maikenp/gambit_aus_fork:
    - file_to_sync.txt
    - source: folder1/
      dest: folder1/
      exclude: |
        sub1/sub2/sub3
        sub1/sub2/sub3/file_to_exclude.txt
    - source: folder2/
      dest: folder2/
    - source: folder3/
      dest: folder3/